# Generated by Django 3.2.5 on 2021-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('author_info', models.CharField(max_length=180, verbose_name='author information')),
                ('article_url', models.URLField(max_length=180, verbose_name='link to article')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='image')),
                ('show_on_main', models.BooleanField(default=False, help_text='choose to display on the home page', verbose_name='show on main page')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-added_at'],
            },
        ),
    ]
