# Generated by Django 3.2.5 on 2021-08-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Meeting place', max_length=100, verbose_name='place')),
                ('meeting_date', models.DateField(verbose_name='meeting date')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('description', models.TextField(help_text='Describe your experience, what you liked/disliked', verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diaries/', verbose_name='image')),
                ('sent_to_curator', models.BooleanField(default=False, help_text='Shows if diary has been sent to curator', verbose_name='sent to curator')),
                ('mark', models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('neutral', 'neutral')], help_text='Rate the time spent', max_length=20, verbose_name='color')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='diary author')),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('author', 'place', 'meeting_date'), name='unique-author-place-date'),
        ),
    ]
