# Generated by Django 3.2.5 on 2021-08-12 17:11

from django.db import migrations, models

import bbbs.books.validators


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='mark',
            field=models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('neutral', 'neutral')], help_text='Rate the time spent', max_length=20, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='meeting_date',
            field=models.DateField(validators=[bbbs.books.validators.diary_year_validator], verbose_name='meeting date'),
        ),
    ]
