# Generated by Django 3.2.5 on 2021-08-08 12:14

import bbbs.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20210808_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('year', models.PositiveSmallIntegerField(validators=[bbbs.common.validators.year_validator], verbose_name='publication date')),
                ('description', models.TextField(max_length=1024, verbose_name='description')),
                ('color', models.CharField(choices=[('#C8D1FF', 'light blue'), ('#FF8585', 'orange')], max_length=7, verbose_name='color')),
                ('url', models.URLField(verbose_name='book url')),
                ('slug', models.SlugField(editable=False, max_length=200, verbose_name='slug')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added_at')),
                ('tags', models.ManyToManyField(related_name='books', to='common.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-added_at'],
            },
        ),
    ]
