# Generated by Django 3.2.5 on 2021-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_city_options'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(help_text='tags appropriate for this event', related_name='events', to='common.Tag', verbose_name='tags'),
        ),
    ]
