# Generated by Django 3.2.5 on 2021-08-15 09:25

import bbbs.common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210815_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'ordering': ['event__start_at', '-registered_at'], 'verbose_name': 'Event participant', 'verbose_name_plural': 'Event participants'},
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', validators=[bbbs.common.validators.event_seats_validator], verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registration date'),
        ),
    ]
