# Generated by Django 3.2.5 on 2021-08-08 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20210808_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.BooleanField(default=False, verbose_name='mentor choice')),
                ('verified', models.BooleanField(default=False, verbose_name='verified by moderator')),
                ('show_on_main', models.BooleanField(default=True, verbose_name='show on main page')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('gender', models.CharField(blank=True, choices=[('M', 'boy'), ('F', 'girl')], max_length=1, null=True, verbose_name='gender')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='age')),
                ('activity_type', models.PositiveSmallIntegerField(choices=[(0, 'active'), (1, 'fun'), (2, 'educative')], verbose_name='activity type')),
                ('description', models.TextField(help_text='share your experience', verbose_name='description')),
                ('link', models.URLField(blank=True, help_text='link to the website', null=True, verbose_name='link')),
                ('image_url', models.ImageField(blank=True, help_text='add image', null=True, upload_to='places/', verbose_name='image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='common.city', verbose_name='city')),
                ('tags', models.ManyToManyField(blank=True, related_name='places', to='common.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Place - where to go?',
                'verbose_name_plural': 'Places - where to go?',
                'ordering': ['-pub_date'],
            },
        ),
    ]
