# Generated by Django 3.2.5 on 2021-08-15 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='users.customuser', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'verified'], name='places_plac_city_id_d55491_idx'),
        ),
    ]
