# Generated by Django 3.2.5 on 2021-08-15 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210815_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='age'),
        ),
    ]
