# Generated by Django 3.2.5 on 2021-08-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to=settings.AUTH_USER_MODEL, verbose_name='curator'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('moderator_reg', 'Regional moderator'), ('moderator', 'Moderator'), ('mentor', 'Mentor'), ('curator', 'Curator')], default='mentor', max_length=30, verbose_name='user role'),
        ),
    ]
