# Generated by Django 3.2.5 on 2021-08-12 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_city_options'),
        ('users', '0002_auto_20210808_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.city'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curator',
            field=models.ForeignKey(blank=True, help_text='choose curator if new user is mentor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to=settings.AUTH_USER_MODEL, verbose_name='curator'),
        ),
    ]
