# Generated by Django 3.2.5 on 2021-08-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('child_name', models.CharField(max_length=70, verbose_name='child name')),
                ('friends_since', models.DateTimeField(verbose_name='friends since')),
                ('show_on_main', models.BooleanField(default=False, help_text='choose to display on the home page', verbose_name='show on main page')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='story added at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='story modified at')),
                ('intro', models.CharField(max_length=200, verbose_name='story intro')),
                ('text', models.TextField(verbose_name='story text')),
                ('quote', models.CharField(max_length=150, verbose_name='quote')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='story author')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-added_at'],
            },
        ),
    ]
