# Generated by Django 3.2.5 on 2021-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='friends_since',
            field=models.DateField(verbose_name='friends since'),
        ),
    ]
