# Generated by Django 3.2.5 on 2021-08-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20210808_1514'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('show_on_main', models.BooleanField(default=False, help_text='choose to display on the home page', verbose_name='show on main page')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='common.Tag', verbose_name='questions')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-added_at'],
            },
        ),
    ]
