# Generated by Django 3.2.5 on 2021-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, max_length=70, unique=True)),
                ('model', models.CharField(choices=[('events', 'tag for events'), ('places', 'tag for places'), ('questions', 'tag for questions'), ('rights', 'tag for rights'), ('books', 'tag for books'), ('movies', 'tag for movies'), ('videos', 'tag for videos')], max_length=50, verbose_name='tag model label')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['model'],
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='primary city'),
        ),
    ]
