# Generated by Django 3.2.5 on 2021-08-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210808_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-is_primary'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
