# Generated by Django 3.2.5 on 2021-08-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('code_iso_3166', models.CharField(choices=[('RU-MOW', 'Moscow'), ('RU-MOS', 'Moskovskaya oblast'), ('RU-SPE', 'Saint Petersburg'), ('RU-LEN', 'Leningradskaya oblast'), ('RU-TVE', 'Tverskaya oblast'), ('RU-SVE', 'Sverdlovskaya oblast'), ('RU-TYU', 'Tyuemenskaya oblast'), ('RU-KOS', 'Kostromskaya oblast'), ('RU-BA', 'Bashkarstan republic'), ('RU-YAR', 'Yaroslavskaya oblast'), ('RU-RYA', 'Ryazanskaya oblast')], max_length=20, verbose_name='iso code choices')),
                ('timezone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='timezone')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='common.region', verbose_name='region'),
        ),
    ]
