# Generated by Django 3.2.5 on 2021-08-17 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_auto_20210817_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added_at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='image')),
                ('link', models.URLField(unique=True, verbose_name='link to video')),
                ('duration_in_seconds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36000)], verbose_name='video duration in seconds')),
                ('show_on_main', models.BooleanField(default=False, help_text='choose to display on the main page', verbose_name='show on main page')),
                ('tags', models.ManyToManyField(related_name='videos', to='common.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-added_at'],
            },
        ),
    ]
