# Generated by Django 3.2.5 on 2021-08-18 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210817_1257'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_in_seconds',
            field=models.PositiveSmallIntegerField(help_text='video duration in seconds, not longer than 10 hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36000)], verbose_name='video duration in seconds'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='common.Tag', verbose_name='tags'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added_at')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('annotation', models.CharField(help_text='movie director, production year etc', max_length=200, verbose_name='annotation')),
                ('link', models.URLField(unique=True, verbose_name='link to the movie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/', verbose_name='image')),
                ('show_on_main', models.BooleanField(default=True, help_text='choose to display on the main page', verbose_name='show on main page')),
                ('tags', models.ManyToManyField(blank=True, related_name='movies', to='common.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-added_at'],
            },
        ),
    ]
